'use client'

import Link from 'next/link'
import { useState } from 'react'
import { login, register, requestPasswordReset, updatePassword } from '@/app/auth/actions'

type Mode = 'login' | 'register' | 'forgot' | 'reset'
export function AuthForm({ mode, returnTo }: { mode: Mode; returnTo?: string }) {
  const [pending, setPending] = useState(false), [message, setMessage] = useState(''), [success, setSuccess] = useState(false)
  async function submit(form: FormData) { setPending(true); setMessage(''); const result = mode === 'login' ? await login({ email: String(form.get('email') || ''), password: String(form.get('password') || ''), returnTo }) : mode === 'register' ? await register({ firstName: String(form.get('firstName') || ''), lastName: String(form.get('lastName') || ''), email: String(form.get('email') || ''), phone: String(form.get('phone') || ''), password: String(form.get('password') || ''), confirmPassword: String(form.get('confirmPassword') || ''), preferredLanguage: (String(form.get('preferredLanguage') || 'pt') === 'en' ? 'en' : 'pt') }) : mode === 'forgot' ? await requestPasswordReset(String(form.get('email') || '')) : await updatePassword(String(form.get('password') || ''), String(form.get('confirmPassword') || '')); setPending(false); setSuccess(result.ok); setMessage(result.ok ? (mode === 'forgot' ? 'Verifique o seu email para continuar.' : 'Operação concluída com sucesso.') : result.message) }
  const title = mode === 'login' ? 'Entrar' : mode === 'register' ? 'Criar conta' : mode === 'forgot' ? 'Recuperar acesso' : 'Nova palavra-passe'
  return <main className="min-h-screen bg-[#f7f9fc] px-4 py-12 text-[#071d3d]"><div className="mx-auto max-w-md rounded-3xl border border-[#dbe4f0] bg-white p-8 shadow-xl"><Link href="/" className="text-sm font-bold tracking-[0.2em] text-[#0b3d91]">PLUTONIUM</Link><h1 className="mt-8 text-3xl font-semibold">{title}</h1><form action={submit} className="mt-8 space-y-4">{mode === 'register' && <div className="grid grid-cols-2 gap-3"><input name="firstName" required placeholder="Nome" className="auth-input"/><input name="lastName" required placeholder="Apelido" className="auth-input"/></div>}{mode === 'register' && <input name="phone" required placeholder="Telefone" className="auth-input"/>}{mode !== 'reset' && <input name="email" type="email" required placeholder="Email" className="auth-input"/>}{mode !== 'forgot' && <input name="password" type="password" minLength={8} required placeholder="Palavra-passe" className="auth-input"/>}{(mode === 'register' || mode === 'reset') && <input name="confirmPassword" type="password" minLength={8} required placeholder="Confirmar palavra-passe" className="auth-input"/>}{mode === 'register' && <select name="preferredLanguage" defaultValue="pt" className="auth-input"><option value="pt">Português</option><option value="en">English</option></select>}<button disabled={pending} className="w-full rounded-xl bg-[#0b3d91] px-4 py-3 font-semibold text-white disabled:opacity-60">{pending ? 'A processar…' : title}</button>{message && <p className={success ? 'text-sm text-emerald-700' : 'text-sm text-red-600'}>{message}</p>}</form><div className="mt-6 flex flex-wrap gap-4 text-sm text-[#0b3d91]">{mode === 'login' && <><a href="/register">Criar conta</a><a href="/forgot-password">Esqueci-me da palavra-passe</a></>}{mode === 'register' && <a href="/login">Já tenho conta</a>}{(mode === 'forgot' || mode === 'reset') && <a href="/login">Voltar a entrar</a>}</div></div></main>
}
