create extension if not exists pgcrypto;

create type public.profile_role as enum ('super_admin','admin','property_manager','agent','investor','buyer','tenant','viewer');
create type public.record_status as enum ('active','inactive','suspended');
create type public.property_type as enum ('apartment','house','villa','townhouse','office','commercial','land','warehouse','development');
create type public.property_category as enum ('luxury','medium','affordable','social_impact','commercial','land');
create type public.property_status as enum ('draft','pending_review','published','reserved','sold','rented','archived');
create type public.media_type as enum ('image','video','360_exterior','360_interior','floorplan','document');
create type public.lead_type as enum ('buyer','tenant','investor','seller','partner','general');
create type public.lead_status as enum ('new','contacted','qualified','viewing','proposal','negotiation','converted','lost');
create type public.appointment_type as enum ('property_viewing','investor_meeting','consultation','virtual_tour');
create type public.appointment_status as enum ('requested','confirmed','completed','cancelled','no_show');
create type public.investment_status as enum ('draft','open','funding','funded','active','completed','cancelled');

create or replace function public.set_updated_at() returns trigger language plpgsql set search_path = public as $$ begin new.updated_at = now(); return new; end $$;

create table public.profiles (id uuid primary key references auth.users(id) on delete cascade, first_name text, last_name text, phone text, avatar_url text, role public.profile_role not null default 'viewer', status public.record_status not null default 'active', preferred_language text not null default 'pt' check (preferred_language in ('pt','en')), country text default 'Angola', created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.organizations (id uuid primary key default gen_random_uuid(), name text not null, slug text not null unique, type text not null default 'agency', status public.record_status not null default 'active', created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.organization_members (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id) on delete cascade, user_id uuid not null references auth.users(id) on delete cascade, role text not null default 'member', created_at timestamptz not null default now(), unique (organization_id,user_id));
create table public.properties (id uuid primary key default gen_random_uuid(), title text not null, title_pt text, title_en text, description text not null default '', description_pt text, description_en text, slug text not null unique, property_type public.property_type not null, category public.property_category not null, status public.property_status not null default 'draft', price numeric(14,2) check (price is null or price >= 0), currency text not null default 'AOA' check (currency in ('AOA','USD','EUR')), country text not null default 'Angola', province text not null, municipality text not null, neighborhood text not null, address text, latitude double precision check (latitude between -90 and 90), longitude double precision check (longitude between -180 and 180), bedrooms integer check (bedrooms is null or bedrooms >= 0), bathrooms numeric(4,1) check (bathrooms is null or bathrooms >= 0), parking_spaces integer check (parking_spaces is null or parking_spaces >= 0), built_area_m2 numeric(12,2) check (built_area_m2 is null or built_area_m2 > 0), land_area_m2 numeric(12,2) check (land_area_m2 is null or land_area_m2 > 0), year_built integer check (year_built is null or year_built between 1800 and 2200), is_featured boolean not null default false, is_verified boolean not null default false, is_published boolean not null default false, owner_id uuid references auth.users(id) on delete set null, agent_id uuid references auth.users(id) on delete set null, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), check (not is_published or status = 'published'));
create table public.property_media (id uuid primary key default gen_random_uuid(), property_id uuid not null references public.properties(id) on delete cascade, media_type public.media_type not null, storage_path text not null, public_url text, alt_text text, sort_order integer not null default 0 check (sort_order >= 0), is_primary boolean not null default false, created_at timestamptz not null default now());
create table public.property_features (id uuid primary key default gen_random_uuid(), property_id uuid not null references public.properties(id) on delete cascade, feature text not null, sort_order integer not null default 0, created_at timestamptz not null default now(), unique(property_id,feature));
create table public.property_favorites (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade, property_id uuid not null references public.properties(id) on delete cascade, created_at timestamptz not null default now(), unique(user_id,property_id));
create table public.property_views (id uuid primary key default gen_random_uuid(), property_id uuid not null references public.properties(id) on delete cascade, user_id uuid references auth.users(id) on delete set null, session_id text, created_at timestamptz not null default now(), check (user_id is not null or session_id is not null));
create table public.investment_projects (id uuid primary key default gen_random_uuid(), title text not null, slug text not null unique, description text not null default '', property_id uuid references public.properties(id) on delete set null, minimum_investment numeric(14,2) not null check (minimum_investment > 0), target_amount numeric(14,2) not null check (target_amount > 0), raised_amount numeric(14,2) not null default 0 check (raised_amount >= 0 and raised_amount <= target_amount), currency text not null default 'AOA', project_status public.investment_status not null default 'draft', expected_return numeric(6,3), investment_period text, risk_disclosure text not null, start_date date, end_date date, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), check (expected_return is null or expected_return >= 0), check (end_date is null or start_date is null or end_date >= start_date));
create table public.leads (id uuid primary key default gen_random_uuid(), name text not null, email text, phone text, company text, source text, property_id uuid references public.properties(id) on delete set null, investment_project_id uuid references public.investment_projects(id) on delete set null, lead_type public.lead_type not null default 'general', status public.lead_status not null default 'new', assigned_to uuid references auth.users(id) on delete set null, notes text, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.inquiries (id uuid primary key default gen_random_uuid(), user_id uuid references auth.users(id) on delete set null, property_id uuid references public.properties(id) on delete set null, investment_project_id uuid references public.investment_projects(id) on delete set null, name text not null, email text not null, phone text, message text not null, status public.lead_status not null default 'new', assigned_to uuid references auth.users(id) on delete set null, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.appointments (id uuid primary key default gen_random_uuid(), user_id uuid references auth.users(id) on delete set null, property_id uuid references public.properties(id) on delete set null, agent_id uuid references auth.users(id) on delete set null, appointment_type public.appointment_type not null, scheduled_at timestamptz not null, status public.appointment_status not null default 'requested', notes text, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.documents (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade, document_type text not null, storage_path text not null, file_name text not null, mime_type text not null, file_size bigint not null check (file_size > 0), status public.record_status not null default 'active', created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.investment_documents (id uuid primary key default gen_random_uuid(), investment_project_id uuid not null references public.investment_projects(id) on delete cascade, document_id uuid not null references public.documents(id) on delete cascade, document_type text not null, created_at timestamptz not null default now(), unique(investment_project_id,document_id));
create table public.investment_interests (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade, investment_project_id uuid not null references public.investment_projects(id) on delete cascade, amount numeric(14,2) not null check (amount > 0), currency text not null default 'AOA', status text not null default 'submitted' check (status in ('submitted','reviewing','approved','declined','withdrawn')), created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.notifications (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade, type text not null, title text not null, message text not null, link text, is_read boolean not null default false, created_at timestamptz not null default now());
create table public.audit_logs (id uuid primary key default gen_random_uuid(), user_id uuid references auth.users(id) on delete set null, action text not null, entity_type text not null, entity_id uuid, old_values jsonb, new_values jsonb, ip_address inet, user_agent text, created_at timestamptz not null default now());
create table public.system_settings (id uuid primary key default gen_random_uuid(), key text not null unique, value jsonb not null default '{}'::jsonb, updated_at timestamptz not null default now());

create index properties_status_published_idx on public.properties(status,is_published); create index properties_discovery_idx on public.properties(category,property_type,province,municipality,neighborhood,price,bedrooms,bathrooms,created_at desc); create index property_media_property_idx on public.property_media(property_id,sort_order); create index property_features_property_idx on public.property_features(property_id,sort_order); create index property_views_property_idx on public.property_views(property_id,created_at desc); create index leads_status_idx on public.leads(status,assigned_to); create index inquiries_user_idx on public.inquiries(user_id,created_at desc); create index appointments_user_idx on public.appointments(user_id,scheduled_at); create index investment_status_idx on public.investment_projects(project_status); create index interests_user_idx on public.investment_interests(user_id,created_at desc); create index notifications_user_idx on public.notifications(user_id,is_read,created_at desc); create index documents_user_idx on public.documents(user_id,created_at desc);

create trigger profiles_updated_at before update on public.profiles for each row execute function public.set_updated_at(); create trigger organizations_updated_at before update on public.organizations for each row execute function public.set_updated_at(); create trigger properties_updated_at before update on public.properties for each row execute function public.set_updated_at(); create trigger investment_projects_updated_at before update on public.investment_projects for each row execute function public.set_updated_at(); create trigger leads_updated_at before update on public.leads for each row execute function public.set_updated_at(); create trigger inquiries_updated_at before update on public.inquiries for each row execute function public.set_updated_at(); create trigger appointments_updated_at before update on public.appointments for each row execute function public.set_updated_at(); create trigger documents_updated_at before update on public.documents for each row execute function public.set_updated_at(); create trigger investment_interests_updated_at before update on public.investment_interests for each row execute function public.set_updated_at(); create trigger system_settings_updated_at before update on public.system_settings for each row execute function public.set_updated_at();

alter table public.profiles enable row level security; alter table public.organizations enable row level security; alter table public.organization_members enable row level security; alter table public.properties enable row level security; alter table public.property_media enable row level security; alter table public.property_features enable row level security; alter table public.property_favorites enable row level security; alter table public.property_views enable row level security; alter table public.leads enable row level security; alter table public.inquiries enable row level security; alter table public.appointments enable row level security; alter table public.investment_projects enable row level security; alter table public.investment_documents enable row level security; alter table public.investment_interests enable row level security; alter table public.documents enable row level security; alter table public.notifications enable row level security; alter table public.audit_logs enable row level security; alter table public.system_settings enable row level security;

create policy properties_public_read on public.properties for select using (is_published = true and status = 'published'); create policy property_media_public_read on public.property_media for select using (exists(select 1 from public.properties p where p.id = property_id and p.is_published and p.status = 'published' and media_type <> 'document')); create policy property_features_public_read on public.property_features for select using (exists(select 1 from public.properties p where p.id = property_id and p.is_published and p.status = 'published'));
create policy profiles_own_read on public.profiles for select using (auth.uid() = id); create policy profiles_own_update on public.profiles for update using (auth.uid() = id) with check (auth.uid() = id); create policy favorites_own_all on public.property_favorites for all using (auth.uid() = user_id) with check (auth.uid() = user_id); create policy views_insert_public on public.property_views for insert with check (user_id is null or auth.uid() = user_id); create policy inquiries_own_read on public.inquiries for select using (auth.uid() = user_id); create policy inquiries_self_insert on public.inquiries for insert with check (user_id is null or auth.uid() = user_id); create policy appointments_own_read on public.appointments for select using (auth.uid() = user_id); create policy appointments_self_insert on public.appointments for insert with check (user_id is null or auth.uid() = user_id); create policy interests_own_all on public.investment_interests for all using (auth.uid() = user_id) with check (auth.uid() = user_id); create policy notifications_own_all on public.notifications for all using (auth.uid() = user_id) with check (auth.uid() = user_id); create policy documents_own_all on public.documents for all using (auth.uid() = user_id) with check (auth.uid() = user_id);

insert into public.properties (title,title_pt,title_en,description,description_pt,description_en,slug,property_type,category,status,price,currency,province,municipality,neighborhood,address,bedrooms,bathrooms,parking_spaces,built_area_m2,land_area_m2,is_featured,is_verified,is_published) values
('Residencial Vista Baía','Residencial Vista Baía','Bay View Residence','Fictional development dataset for testing only.','Dataset fictício para testes internos.','Fictional development dataset for testing only.','residencial-vista-baia','apartment','luxury','published',185000000,'AOA','Luanda','Talatona','Talatona Sul','Rua de Demonstração 1',3,3,2,220,null,true,true,true),
('Casa Jardim Maianga','Casa Jardim Maianga','Maianga Garden House','Fictional development dataset for testing only.','Dataset fictício para testes internos.','Fictional development dataset for testing only.','casa-jardim-maianga','house','medium','published',92000000,'AOA','Luanda','Maianga','Maianga Centro','Rua de Demonstração 2',4,3,2,260,420,true,true,true),
('Kilamba Central','Kilamba Central','Kilamba Central','Fictional development dataset for testing only.','Dataset fictício para testes internos.','Fictional development dataset for testing only.','kilamba-central','apartment','affordable','published',38000000,'AOA','Luanda','Kilamba','Kilamba Central','Avenida de Demonstração 3',2,2,1,94,null,false,true,true),
('Vila Social Impacto','Vila Social Impacto','Social Impact Village','Fictional development dataset for testing only.','Dataset fictício para testes internos.','Fictional development dataset for testing only.','vila-social-impacto','development','social_impact','published',650000000,'AOA','Luanda','Viana','Zango 8','Estrada de Demonstração 4',null,null,null,12000,18000,false,false,true),
('Benfica Horizonte','Benfica Horizonte','Benfica Horizon','Fictional development dataset for testing only.','Dataset fictício para testes internos.','Fictional development dataset for testing only.','benfica-horizonte','villa','luxury','published',240000000,'AOA','Luanda','Belas','Benfica','Rua de Demonstração 5',5,5,3,420,900,true,true,true),
('Camama Terreno Demo','Camama Terreno Demo','Camama Demo Land','Fictional development dataset for testing only.','Dataset fictício para testes internos.','Fictional development dataset for testing only.','camama-terreno-demo','land','land','draft',15000000,'AOA','Luanda','Camama','Camama Norte','Zona de Demonstração 6',null,null,null,null,2500,false,false,false),
('Ingombota Business Hub','Ingombota Business Hub','Ingombota Business Hub','Fictional development dataset for testing only.','Dataset fictício para testes internos.','Fictional development dataset for testing only.','ingombota-business-hub','office','commercial','published',310000000,'AOA','Luanda','Ingombota','Baixa','Avenida de Demonstração 7',null,2,8,1800,null,false,true,true),
('Zango Warehouse Demo','Zango Warehouse Demo','Zango Demo Warehouse','Fictional development dataset for testing only.','Dataset fictício para testes internos.','Fictional development dataset for testing only.','zango-warehouse-demo','warehouse','commercial','pending_review',175000000,'AOA','Luanda','Viana','Zango 3','Rua de Demonstração 8',null,2,4,3200,6000,false,false,false);

insert into storage.buckets (id,name,public) values ('plutonium-public','plutonium-public',true),('plutonium-private','plutonium-private',false) on conflict (id) do nothing;
create policy plutonium_public_read on storage.objects for select using (bucket_id = 'plutonium-public');
create policy plutonium_public_auth_insert on storage.objects for insert to authenticated with check (bucket_id = 'plutonium-public' and (storage.foldername(name))[1] in ('branding','properties'));
create policy plutonium_private_own_read on storage.objects for select to authenticated using (bucket_id = 'plutonium-private' and (storage.foldername(name))[1] = 'users' and (storage.foldername(name))[2] = (select auth.uid()::text));
create policy plutonium_private_own_insert on storage.objects for insert to authenticated with check (bucket_id = 'plutonium-private' and (storage.foldername(name))[1] = 'users' and (storage.foldername(name))[2] = (select auth.uid()::text));
